// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reader.Data;

namespace Reader.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210304161842_Ulong")]
    partial class Ulong
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Reader.Entity.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Antenna")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Epc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("LastSeenTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RaceName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
